api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: true
      targetPort: {{ targetPortOrDefault 8080 }}
      transport: http
      allowInsecure: false
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: connectionstrings--productcontext
        value: Server=tcp:{{ .Env.SQLSERVER_SQLSERVERFQDN }},1433;Encrypt=True;Authentication="Active Directory Default";Database=ProductContext
      - name: connectionstrings--cache
        value: '{{ .Env.CACHE_CONNECTIONSTRING }}'
      - name: connectionstrings--openai
        value: '{{ .Env.OPENAI_CONNECTIONSTRING }}'
      - name: connectionstrings--textembedding
        value: '{{ .Env.OPENAI_TEXTEMBEDDINGNAME }}'
      - name: connectionstrings--gpt4
        value: '{{ .Env.OPENAI_GPTNAME }}'                 
      - name: connectionstrings--redisvss
        value: '{{ .Env.REDISVSS_CONNECTIONSTRING }}'
  template:
    containers:
      - image: {{ .Image }}
        name: products
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: HTTP_PORTS
            value: '{{ targetPortOrDefault 0 }}'
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: ConnectionStrings__ProductContext
            secretRef: connectionstrings--productcontext
          - name: ConnectionStrings__cache
            secretRef: connectionstrings--cache
          - name: ConnectionStrings__openai
            secretRef: connectionstrings--openai
          - name: ConnectionStrings__textembedding
            secretRef: connectionstrings--textembedding 
          - name: ConnectionStrings__gpt4
            secretRef: connectionstrings--gpt4              
          - name: ConnectionStrings__redisvss
            secretRef: connectionstrings--redisvss
    scale:
      minReplicas: 1
tags:
  azd-service-name: products
  aspire-resource-name: products
